blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    path('users/', include('users.urls')),
    path('tags/', include('tags.urls')),
    path('comments/', include('comments.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from posts.views import index,create,update,delete,detail

urlpatterns = [
    path('', index, name='index'),
    path('create/', create, name = 'create'),
    path('update/<int:id>/', update, name = 'update'),
    path('delete/<int:id>', delete,name = 'delete'),
    path('detail/<int:id>', detail, name='detail'),
]

posts/models.py
from django.db import models
from django.contrib.auth.models import User

class Post(models.Model):
    title = models.CharField(max_length=155)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    creat_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to = 'images')

    def __str__(self):
        return f'{self.title}======={self.creat_at}'

    def get_parent(self):
        return self.comment_post.filter(parent__isnull=True)

class Like(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name='like_user')
    post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='like_post')

    def __str__(self):
        return self.user.username

tags/models.py
from django.db import models
from posts.models import Post

class Tag(models.Model):
    title = models.CharField(max_length=255)
    posts = models.ManyToManyField(Post,verbose_name='tags')

    def __str__(self):
        return self.title

posts/views.py
from django.db.models.query import RawQuerySet
from django.shortcuts import render,redirect
from posts.models import Post,Like
from tags.models import Tag
from comments.models import Comment
from django.db.models import Q

def index(request):
    if 'key_word' in request.GET:
        key = request.GET.get('words')
        posts = Post.objects.filter(Q(title__icontains=key) | Q(user__username__icontains=key))
    else:
        posts = Post.objects.all()
    return render(request, 'posts/index.html', {'posts':posts})

def create(request):
    if request.method == "POST":
        title = request.POST.get('title')
        text = request.POST.get('text')
        file = request.FILES.get('file')
        tags = request.POST.get('tags')
        post_obj = Post.objects.create(user=request.user,title = title, text = text,image=file)
        if len(tags) != 0:
            try:
                tags_get = Tag.objects.get(title = tags)
                tags_get.posts.add(post_obj)
            except:
                tags_get = Tag.objects.create(title=tags)
                tags_get.posts.add(post_obj)
        return redirect('index')    
    return render(request, 'posts/create.html')

def update(request, id):
    if request.method == 'POST':
        title = request.POST.get('title')
        text = request.POST.get('text')
        file = request.FILES.get('file')
        tags = request.POST.get('tag')
        post_update = Post.objects.get(id=id)
        post_update.title = title
        post_update.text = text
        post_update.image = file
        post_update.save()
        if len(tags) != 0:
            try:
                tags_get = Tag.objects.get(title = tags)
                tags_get.posts.add(post_update)
            except:
                tags_obj = Tag.objects.create(title=tags)
                tags_obj.posts.add(post_update)
        return redirect('index')   
    return render(request, 'posts/update.html')

def delete(request, id):
    if request.method == 'POST':
        post_object = Post.objects.get(id = id)
        post_object.delete()
        return redirect('index')
    return render(request, 'posts/delete.html')

def detail(request,id):
    posts = Post.objects.get(id=id)
    if request.method == 'POST':
        if 'comment' in request.POST:
            try:
                text = request.POST.get('text')
                comment_obj = Comment.objects.create(user=request.user, post=posts, text=text)
                return redirect('detail', posts.id)
            except:
                print('Error')
        if 'comments_comment' in request.POST:
            id = int(request.POST.get('comments_comment'))
            print(id)
            comment_obj = Comment.objects.get(id=id)
            try:
                text = request.POST.get('text')
                comment_create = Comment.objects.create(user=request.user, post=posts,text=text,parent=comment_obj)
                return redirect('detail', posts.id)
            except:
                print('ERROR')
        if 'like' in request.POST:
            try:
                like = Like.objects.get(user=request.user,post = posts)
                like.delete()
            except:
                Like.objects.create(user = request.user, post=posts)
    return render(request, 'posts/detail.html', {"posts":posts})

templates/posts/create.html
{% extends 'base.html' %}
{% block content  %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="container">
        <div class="mb-3">
            <label for="formGroupExampleInput" class="form-label">Title</label>
            <input type="text" name="title" class="form-control" id="formGroupExampleInput"
                   placeholder="Example input placeholder">
        </div>
        <div class="mb-3">
            <label for="formGroupExampleInput2" class="form-label">Text</label>      
            <input type="text" name="text" class="form-control" id="formGroupExampleInput2"
                   placeholder="An other input placeholder">
        </div>
        <div class="mb-3">
            <div class="form-group">
                <label for="exampleFormControlFile1">Choice file</label>
                <input type="file" name="file" class="form-control-file" id="exampleFormControlFile1">
            </div>
        </div>
        <div class="mb-3">
            <label for="formGroupExampleInput" class="form-label">Tags</label>
            <input type="text" name="tags" class="form-control" id="formGroupExampleInput"
                   placeholder="Example input placeholder">
        </div>
        <div class="container">
            <button class="btn btn-primary active" type="submit">CREATE</button>
        </div>
    </div>
</form>
{% endblock %}

templates/posts/detail.html
{% extends 'index.html' %}
{% load static %}
{% block content %}
    <div class="col-lg-8">
        <div class="main_blog_details">
            <img class="img-fluid" src="{{ posts.image.url }}" alt="">
            <h4>{{ posts.title }}</h4>
            <div class="user_details">
                <div class="float-left">
                    {% for tag in posts.tag_set.all %}
                        <a href="{% url 'detail_tag' tag.id %}">{{ tag.title }}</a>
                    {% endfor %}
                </div>
                <div class="float-right">
                    <div class="media">
                        <div class="media-body">
                            <h5>{{ posts.user }}</h5>
                            <p>{{ posts.crate_at }}</p>
                        </div>
                        <div class="d-flex">
                            <img src="{% static 'img/blog/user-img.jpg' %}" alt="">
                        </div>
                    </div>
                </div>
            </div>
            <p>{{ posts.description }}</p>
            <hr>
            {% if user.is_authenticated %}
                <div class="container">
                    <a href="{% url 'update' posts.id %}">
                        <button class="btn btn-success">Update</button>
                    </a>
                    <a href="{% url 'delete' posts.id %}">
                        <button class="btn btn-danger">Delete</button>
                    </a>

                </div>
            {% else %}
            {% endif %}
            <div class="news_d_footer">
                <form method="post">
                    {% csrf_token %}
                    <input type="hidden" name="like">
                    <button type="submit" class="btn btn-primary">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                             class="bi bi-heart-fill" viewBox="0 0 16 16">
                            <path fill-rule="evenodd"
                                  d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/>
                        </svg>
                    </button>
                </form>
                <div class="ml-3">
                    </i>{{ posts.like_post.all.count }} people like this
                </div>
                <a class="justify-content-center ml-auto" href="#">
                    <i class="lnr lnr lnr-bubble"></i>{{ posts.comment.all.count }}
                    Comments</a>
                <div class="news_socail ml-auto">
                    <a href="#"><i class="fa fa-facebook"></i></a>
                    <a href="#"><i class="fa fa-twitter"></i></a>
                    <a href="#"><i class="fa fa-pinterest"></i></a>
                    <a href="#"><i class="fa fa-rss"></i></a>
                </div>
            </div>
        </div>
        <div class="navigation-area">
            <div class="row">
                <div class="col-lg-6 col-md-6 col-12 nav-left flex-row d-flex justify-content-start align-items-center">
                    <div class="thumb">
                        <a href="#"><img class="img-fluid" src="img/blog/prev.jpg" alt=""></a>
                    </div>
                    <div class="arrow">
                        <a href="#"><span class="lnr text-white lnr-arrow-left"></span></a>
                    </div>
                    <div class="detials">
                        <p>Prev Post</p>
                        <a href="#">
                            <h4>A Discount Toner</h4>
                        </a>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6 col-12 nav-right flex-row d-flex justify-content-end align-items-center">
                    <div class="detials">
                        <p>Next Post</p>
                        <a href="#">
                            <h4>Cartridge Is Better</h4>
                        </a>
                    </div>
                    <div class="arrow">
                        <a href="#"><span class="lnr text-white lnr-arrow-right"></span></a>
                    </div>
                    <div class="thumb">
                        <a href="#"><img class="img-fluid" src="img/blog/next.jpg" alt=""></a>
                    </div>
                </div>
            </div>
        </div>
        <div class="comments-area">
            <h4>{{ posts.comment.all.count }} Comments</h4>
            {% for comment in posts.get_parent %}
                <div class="comment-list">
                    <div class="single-comment justify-content-between d-flex">
                        <div class="user justify-content-between d-flex">
                            <div class="thumb">
                                <img src="img/blog/c1.jpg" alt="">
                            </div>
                            <div class="desc">
                                <h5><a href="#">{{ comment.user }}</a></h5>
                                <p class="date">December 4, 2017 at 3:12 pm </p>
                                <p class="comment">
                                    {{ comment.text }}
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
                    {% for reply in comment.comments_comment.all %}
                        <div class="comment-list left-padding">
                            <div class="single-comment justify-content-between d-flex">
                                <div class="user justify-content-between d-flex">
                                    <div class="thumb">
                                        <img src="img/blog/c2.jpg" alt="">
                                    </div>
                                    <div class="desc">
                                        <h5><a href="#">{{ reply.user }}</a></h5>
                                        <p class="date">December 4, 2017 at 3:12 pm </p>
                                        <p class="comment">
                                            {{ reply.text }}
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                    <form method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <input type="hidden" name="comments_comment" value="{{ comment.id }}">
                            <textarea class="form-control mb-10" rows="5" name="text" placeholder="Messege"
                                    onfocus="this.placeholder = ''" onblur="this.placeholder = 'Messege'"
                                    required=""></textarea>
                        </div>
                        <button type="submit" class="btn btn-success">Send comment</button>
                    </form>
            {% endfor %}
        </div>
        <div class="comment-form">
            <h4>Comment</h4>
            {% if user.is_authenticated %}
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <input type="hidden" name="comment">
                        <textarea class="form-control mb-10" rows="5" name="text" placeholder="Messege"
                                  onfocus="this.placeholder = ''" onblur="this.placeholder = 'Messege'"
                                  required=""></textarea>
                    </div>
                    <button type="submit" class="btn btn-success">Send comment</button>
                </form>
            {% else %}
                <h4 style="color: red">Login user or Register to send message</h4>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/posts/index.html
{% extends 'index.html' %}
{% block content %}
{% for post in posts %}
<div class="col-lg-6 col-md-6">
    <div class="single-post-item">
        <div class="post-thumb">
            {% if post.image %}
            <img class="img-fluid" src="{{ post.image.url }}" alt="">
            {% else %}
            <img class="img-fluid" src="..." alt="">
            {% endif %}
        </div>
        <div class="post-details">
            <h4><a href="{% url 'detail' post.id %}">{{ post.title }}</a></h4>
            <p>{{ post.text|truncatewords:10 }}</p>
            <div class="blog-meta">
                <a href="#" class="m-gap"><span class="lnr lnr-calendar-full"></span>{{ post.create_at }}</a>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

templates/posts/update.html
{% extends 'index.html' %}
{% block content  %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="container">
        <div class="mb-3">
            <label for="formGroupExampleInput" class="form-label">Title</label>
            <input type="text" name="title" class="form-control" id="formGroupExampleInput"
                   placeholder="Example input placeholder">
        </div>
        <div class="mb-3">
            <label for="formGroupExampleInput2" class="form-label">Text</label>      
            <input type="text" name="text" class="form-control" id="formGroupExampleInput2"
                   placeholder="Another input placeholder">
        </div>
        <div class="mb-3">
            <div class="form-group">
                <label for="exampleFormControlFile1">Choice file</label>
                <input type="file" name="file" class="form-control-file" id="exampleFormControlFile1">
            </div>
        </div>
        <div class="mb-3">
            <label for="formGroupExampleInput" class="form-label">Tag</label>
            <input type="text" name="tag" class="form-control" id="formGroupExampleInput"
                   placeholder="Example input placeholder">
        </div>
        <div class="container">
            <button class="btn btn-primary active" type="submit">UPDATE</button>
        </div>
    </div>
</form>
{% endblock %}